### ISSUE TITLE
OpenAI.Threads.FileCitation.file_id error when trying to get messages from assistant

### ISSUE THREAD

**Issue by gertbus** [RageAgainstThePixel/OpenAI-DotNet#180] opened 2023-11-23 15:37 UTC
# Bug Report

## Overview

I keep getting the same error when retrieving the message after the run is Completed. 

You can use the following code to easily reproduce the problem :

using System.Threading;

using OpenAI;
using OpenAI.Assistants;
using OpenAI.Threads;

var api = new OpenAIClient ( "Your_API_KEY" );

var assistant = await api.AssistantsEndpoint.RetrieveAssistantAsync ( "Your_Assistant_ID" );
Console.WriteLine ( $"{assistant} -> {assistant.CreatedAt}" );

var messages = new List<Message> { new Message("What do you know about everything?" )};
var threadRequest = new CreateThreadRequest ( messages );
var run = await assistant.CreateThreadAndRunAsync ( threadRequest );
Console.WriteLine ( $"Created thread and run: {run.ThreadId} -> {run.Id} -> {run.CreatedAt}" );

run = await run.WaitForStatusChangeAsync ();
var thread = await api.ThreadsEndpoint.RetrieveThreadAsync ( run.ThreadId );

Console.WriteLine ( $"Run status changed: {run.Status} -> {run.CreatedAt}" );

// Status is completed here, so U can list the messages

var messageList = await thread.ListMessagesAsync ();

foreach (var message in messageList.Items)
{
    Console.WriteLine ( $"{message.Id}: {message.Role}: {message.PrintContent ()}" );
}
![Issue](https://github.com/RageAgainstThePixel/OpenAI-DotNet/assets/128687307/a8d13020-fc48-4eec-9770-afd1d7c3fea3)

**Comment by StephenHodgson** [comment] 2023-11-23 15:37
Duplicate of #178 fixed in #179

**Closed by StephenHodgson** 2023-11-23 15:37 UTC
Labels: bug

**Comment by gertbus** [comment] 2023-11-23 15:42
Awesome for this fast response! Can i already update it in VS?
