### ISSUE TITLE
Completition and ChatCompletition stream_options

### ISSUE THREAD

**Issue by AissistmeMT** [RageAgainstThePixel/OpenAI-DotNet#310] opened 2024-05-22 06:41 UTC
# Feature Request

Add support of stream_options

## Additional context
[[Usage stats now available when using streaming](https://community.openai.com/t/usage-stats-now-available-when-using-streaming-with-the-chat-completions-api-or-completions-api/738156)](https://community.openai.com/t/usage-stats-now-available-when-using-streaming-with-the-chat-completions-api-or-completions-api/738156)

Thanks!

**Comment by StephenHodgson** [comment] 2024-05-22 12:08
Duplicate of #285

**Closed by StephenHodgson** 2024-05-22 12:08 UTC
Labels: enhancement
